#!/bin/bash

export OPSCENTERD_LOG_STDOUT=1
TWISTD_EXTRA="$TWISTD_EXTRA -n"

REACTOR="-r epoll"

export HOME=$OPSC_HOME

cd $HOME


PY_ARCH="amd64"

PYTHON=/usr/bin/python2.7

[ -n "$PYTHON" ] || {
    echo "No python interpreter found. Abort." >&2
    exit 3
}

PY_VER=$($PYTHON -c "import platform; v = platform.python_version(); print v[:v.index('.', 2)]")
PY_DISTRO="./lib/py-unpure"

export PYTHONPATH="./src:\
/usr/lib/python${PY_VER}/site-packages:\
./src/lib/python${PY_VER}/site-packages:\
./lib/python${PY_VER}/site-packages:\
./lib/py:\
${PY_DISTRO}:\
${PYTHONPATH}:"

export OPSCENTERD_CONFIG_DIR="${OPSC_HOME}/conf"

[ -n "$OPSCENTERD_CONFIG_DIR" ] || {
    echo "Could not find OpsCenter config dir." >&2
    exit 4
}

TWISTD="/usr/bin/twistd"
export PYTHONPATH="${PYTHONPATH}:$OPSC_HOME/lib/py-unpure/"

"$PYTHON" $TWISTD $TWISTD_EXTRA $REACTOR -oy bin/start_opscenter.py
