#!/bin/bash
set -e

function shut_down() {
    echo "Shutting down"
    # if you start background processes in this script, kill them politely with sth. like
    kill -TERM $opspid 2>/dev/null
}

trap "shut_down" SIGKILL SIGTERM SIGHUP SIGINT EXIT

export OPSCENTERD_LOG_STDOUT=1
TWISTD_EXTRA="$TWISTD_EXTRA -n"

REACTOR="-r epoll"

export HOME=$OPSC_HOME

cd $HOME

PY_ARCH="amd64"

PYTHON=/usr/bin/python2.7

[ -n "$PYTHON" ] || {
    echo "No python interpreter found. Abort." >&2
    exit 3
}

PY_VER=$($PYTHON -c "import platform; v = platform.python_version(); print v[:v.index('.', 2)]")
PY_DISTRO="./lib/py-unpure"

export PYTHONPATH="./src:\
/usr/lib/python${PY_VER}/site-packages:\
./src/lib/python${PY_VER}/site-packages:\
./lib/python${PY_VER}/site-packages:\
./lib/py:\
${PY_DISTRO}:\
${PYTHONPATH}:"

export OPSCENTERD_CONFIG_DIR="${OPSC_HOME}/conf"

[ -n "$OPSCENTERD_CONFIG_DIR" ] || {
    echo "Could not find OpsCenter config dir." >&2
    exit 4
}

cat <<EOF> ${OPSCENTERD_CONFIG_DIR}/opscenterd.conf
# opscenterd.conf

[webserver]
port = 8888
interface = 0.0.0.0
# The following settings can be used to enable ssl support for the opscenter
# web application. Change these values to point to the ssl certificate and key
# that you wish to use for your OpsCenter install, as well as the port you would like
# to serve ssl traffic from.
#ssl_keyfile = /var/lib/opscenter/ssl/opscenter.key
#ssl_certfile = /var/lib/opscenter/ssl/opscenter.pem
#ssl_port = 8443

[logging]
# level may be TRACE, DEBUG, INFO, WARN, or ERROR
level = INFO

[authentication]
# Set this option to True to enable OpsCenter authentication.  A default admin
# account will be created with the username "admin" and password "admin".
# Accounts and roles can then be created and modified from within the web UI.
enabled = True

# To help us better understand the needs of users and to improve OpsCenter, OpsCenter
# reports information about itself and the clusters it manages to a central DataStax
# server.  This information is reported anonymously, and potentially sensitive
# information, such as IP addresses, are hashed in a non-reversible way:
# http://www.datastax.com/documentation/opscenter/help/statsReporterProperties.html
[stat_reporter]
# The interval setting determines how often statistics are reported.  To disable
# reporting, set to 0
# interval = 86400 # 24 hours
interval = 0

[agents]
use_ssl = false

EOF

mkdir -p ${OPSCENTERD_CONFIG_DIR}/clusters

cat <<EOF> ${OPSCENTERD_CONFIG_DIR}/clusters/${CLUSTER_NAME}.conf
[cassandra]
username = cassandra
password = ${CASS_PASS}
seed_hosts = ${SEEDS}
api_port = 9160
EOF

TWISTD="/usr/bin/twistd"
export PYTHONPATH="${PYTHONPATH}:$OPSC_HOME/lib/py-unpure/"

# start opscenter and remember its PID
exec "$PYTHON" $TWISTD $TWISTD_EXTRA $REACTOR -oy bin/start_opscenter.py &
opsid=$!

sleep 4

printf "\n\nPress <Ctrl-C> to end the process ...\n\n"

wait
